version: "3.7"

services:
    smake:
      build: 
        context: .
        dockerfile: DockerFile
      ports:
        - "5500:5500"
      volumes:
        - ../:/app
      environment:
        - TZ=UTC
      tty: true
